# Site Settings
title: Start Jekyll
email: arman2@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/jekyll/"
url: "http://rmanak.github.io/jekyll"
port: 5000
safe: true
twitter_username: arman2
github_username:  rmanak
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
