highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
rdiscount:
   extensions: [smart]
permalink: /:title.html
paginate: 6
gems: [jekyll-paginate]
port: 5000
safe: true
url: http://rmanak.github.io/jekyll
autor: Arman Akbarian

baseurl: /jekyll/
title: Testing jekkly
name: Arman Akbarian
email: arman2@gmail.com
description: >
  A guide to getting started with Jekyll.
safe: true
twitter_username: arman2
github_username:  rmanak
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']

