# Site Settings
title: Start Jekyll
email: arman2@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/jekyll"
url: "http://rmanak.github.io"
twitter_username: taniarascia
github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
