# Site Settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 5000
safe: true

baseurl: /jekyll/
title: Testing jekkly
name: Arman Akbarian
email: arman2@gmail.com
description: >
  A guide to getting started with Jekyll.
url: "http://rmanak.github.io/jekyll"
safe: true
twitter_username: arman2
github_username:  rmanak
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']

